/**
 * foodDatabase.js
 * Nutrition values are per `servingSize` of `servingUnit`.
 * Scaling: multiplier = enteredQty / servingSize
 */

export const CATEGORY_ORDER = [
  "Rice & Noodle Dishes",
  "Malaysian & Asian",
  "Western & Fast Food",
  "Protein & Meat",
  "Grains & Cereals",
  "Bread & Bakery",
  "Vegetables",
  "Fruits",
  "Dairy",
  "Nuts & Seeds",
  "Beverages",
  "Snacks & Desserts",
  "Supplements",
];

/** @type {Record<string, { category:string, servingSize:number, servingUnit:string, calories:number, protein:number, carbs:number, fat:number, fiber:number }>} */
export const FOOD_DATABASE = {
  // ── Rice & Noodle Dishes ─────────────────────────────────────────────────
  "chicken rice": {
    category: "Rice & Noodle Dishes",
    servingSize: 1,
    servingUnit: "plate",
    calories: 600,
    protein: 35,
    carbs: 65,
    fat: 15,
    fiber: 2,
  },
  "nasi goreng": {
    category: "Rice & Noodle Dishes",
    servingSize: 1,
    servingUnit: "plate",
    calories: 650,
    protein: 18,
    carbs: 80,
    fat: 22,
    fiber: 2,
  },
  "fried rice": {
    category: "Rice & Noodle Dishes",
    servingSize: 1,
    servingUnit: "plate",
    calories: 650,
    protein: 16,
    carbs: 82,
    fat: 20,
    fiber: 2,
  },
  "char kway teow": {
    category: "Rice & Noodle Dishes",
    servingSize: 1,
    servingUnit: "plate",
    calories: 750,
    protein: 22,
    carbs: 90,
    fat: 28,
    fiber: 3,
  },
  "mee goreng": {
    category: "Rice & Noodle Dishes",
    servingSize: 1,
    servingUnit: "plate",
    calories: 600,
    protein: 18,
    carbs: 78,
    fat: 20,
    fiber: 3,
  },
  "wonton noodle soup": {
    category: "Rice & Noodle Dishes",
    servingSize: 1,
    servingUnit: "bowl",
    calories: 400,
    protein: 20,
    carbs: 55,
    fat: 10,
    fiber: 2,
  },
  "pan mee": {
    category: "Rice & Noodle Dishes",
    servingSize: 1,
    servingUnit: "bowl",
    calories: 450,
    protein: 22,
    carbs: 58,
    fat: 12,
    fiber: 3,
  },
  "economy rice": {
    category: "Rice & Noodle Dishes",
    servingSize: 1,
    servingUnit: "plate",
    calories: 550,
    protein: 20,
    carbs: 65,
    fat: 18,
    fiber: 3,
  },
  "white rice": {
    category: "Rice & Noodle Dishes",
    servingSize: 1,
    servingUnit: "cup",
    calories: 200,
    protein: 4,
    carbs: 44,
    fat: 0,
    fiber: 1,
  },
  "brown rice": {
    category: "Rice & Noodle Dishes",
    servingSize: 1,
    servingUnit: "cup",
    calories: 215,
    protein: 5,
    carbs: 45,
    fat: 2,
    fiber: 3,
  },
  congee: {
    category: "Rice & Noodle Dishes",
    servingSize: 1,
    servingUnit: "bowl",
    calories: 150,
    protein: 5,
    carbs: 30,
    fat: 1,
    fiber: 1,
  },
  "curry mee": {
    category: "Rice & Noodle Dishes",
    servingSize: 1,
    servingUnit: "bowl",
    calories: 600,
    protein: 20,
    carbs: 60,
    fat: 30,
    fiber: 3,
  },
  "mee rebus": {
    category: "Rice & Noodle Dishes",
    servingSize: 1,
    servingUnit: "plate",
    calories: 500,
    protein: 16,
    carbs: 70,
    fat: 16,
    fiber: 4,
  },
  "mee siam": {
    category: "Rice & Noodle Dishes",
    servingSize: 1,
    servingUnit: "plate",
    calories: 480,
    protein: 14,
    carbs: 68,
    fat: 16,
    fiber: 3,
  },
  "asam laksa": {
    category: "Rice & Noodle Dishes",
    servingSize: 1,
    servingUnit: "bowl",
    calories: 450,
    protein: 18,
    carbs: 62,
    fat: 14,
    fiber: 3,
  },
  "lor mee": {
    category: "Rice & Noodle Dishes",
    servingSize: 1,
    servingUnit: "bowl",
    calories: 550,
    protein: 20,
    carbs: 65,
    fat: 20,
    fiber: 2,
  },
  "hokkien mee": {
    category: "Rice & Noodle Dishes",
    servingSize: 1,
    servingUnit: "plate",
    calories: 650,
    protein: 22,
    carbs: 75,
    fat: 26,
    fiber: 3,
  },
  "koay teow th'ng": {
    category: "Rice & Noodle Dishes",
    servingSize: 1,
    servingUnit: "bowl",
    calories: 380,
    protein: 18,
    carbs: 55,
    fat: 8,
    fiber: 2,
  },
  "nasi kandar": {
    category: "Rice & Noodle Dishes",
    servingSize: 1,
    servingUnit: "plate",
    calories: 750,
    protein: 28,
    carbs: 85,
    fat: 32,
    fiber: 3,
  },
  "nasi briyani": {
    category: "Rice & Noodle Dishes",
    servingSize: 1,
    servingUnit: "plate",
    calories: 700,
    protein: 30,
    carbs: 80,
    fat: 28,
    fiber: 3,
  },
  "nasi ayam penyet": {
    category: "Rice & Noodle Dishes",
    servingSize: 1,
    servingUnit: "plate",
    calories: 720,
    protein: 32,
    carbs: 75,
    fat: 30,
    fiber: 3,
  },
  "nasi campur": {
    category: "Rice & Noodle Dishes",
    servingSize: 1,
    servingUnit: "plate",
    calories: 600,
    protein: 24,
    carbs: 70,
    fat: 22,
    fiber: 3,
  },
  "yong tau foo": {
    category: "Rice & Noodle Dishes",
    servingSize: 1,
    servingUnit: "bowl",
    calories: 350,
    protein: 22,
    carbs: 30,
    fat: 14,
    fiber: 4,
  },
  "wantan mee (dry)": {
    category: "Rice & Noodle Dishes",
    servingSize: 1,
    servingUnit: "plate",
    calories: 450,
    protein: 18,
    carbs: 60,
    fat: 14,
    fiber: 2,
  },
  "kolo mee": {
    category: "Rice & Noodle Dishes",
    servingSize: 1,
    servingUnit: "plate",
    calories: 420,
    protein: 16,
    carbs: 58,
    fat: 14,
    fiber: 2,
  },

  // ── Malaysian & Asian ────────────────────────────────────────────────────
  "nasi lemak": {
    category: "Malaysian & Asian",
    servingSize: 1,
    servingUnit: "plate",
    calories: 700,
    protein: 20,
    carbs: 75,
    fat: 35,
    fiber: 3,
  },
  laksa: {
    category: "Malaysian & Asian",
    servingSize: 1,
    servingUnit: "bowl",
    calories: 600,
    protein: 24,
    carbs: 68,
    fat: 22,
    fiber: 3,
  },
  "bak kut teh": {
    category: "Malaysian & Asian",
    servingSize: 1,
    servingUnit: "bowl",
    calories: 500,
    protein: 35,
    carbs: 20,
    fat: 28,
    fiber: 1,
  },
  "roti canai": {
    category: "Malaysian & Asian",
    servingSize: 1,
    servingUnit: "piece",
    calories: 300,
    protein: 7,
    carbs: 40,
    fat: 13,
    fiber: 2,
  },
  "roti prata": {
    category: "Malaysian & Asian",
    servingSize: 1,
    servingUnit: "piece",
    calories: 300,
    protein: 7,
    carbs: 40,
    fat: 13,
    fiber: 2,
  },
  "teh tarik": {
    category: "Malaysian & Asian",
    servingSize: 1,
    servingUnit: "cup",
    calories: 130,
    protein: 4,
    carbs: 20,
    fat: 4,
    fiber: 0,
  },
  milo: {
    category: "Malaysian & Asian",
    servingSize: 1,
    servingUnit: "cup",
    calories: 120,
    protein: 3,
    carbs: 22,
    fat: 3,
    fiber: 1,
  },
  satay: {
    category: "Malaysian & Asian",
    servingSize: 5,
    servingUnit: "sticks",
    calories: 200,
    protein: 20,
    carbs: 8,
    fat: 10,
    fiber: 1,
  },
  rendang: {
    category: "Malaysian & Asian",
    servingSize: 1,
    servingUnit: "serving",
    calories: 400,
    protein: 28,
    carbs: 12,
    fat: 28,
    fiber: 2,
  },
  "curry chicken": {
    category: "Malaysian & Asian",
    servingSize: 1,
    servingUnit: "serving",
    calories: 350,
    protein: 25,
    carbs: 18,
    fat: 20,
    fiber: 2,
  },
  dhal: {
    category: "Malaysian & Asian",
    servingSize: 1,
    servingUnit: "serving",
    calories: 200,
    protein: 11,
    carbs: 30,
    fat: 5,
    fiber: 8,
  },
  sambal: {
    category: "Malaysian & Asian",
    servingSize: 1,
    servingUnit: "tbsp",
    calories: 50,
    protein: 1,
    carbs: 8,
    fat: 2,
    fiber: 2,
  },
  tofu: {
    category: "Malaysian & Asian",
    servingSize: 100,
    servingUnit: "g",
    calories: 80,
    protein: 9,
    carbs: 2,
    fat: 4,
    fiber: 0,
  },
  tempeh: {
    category: "Malaysian & Asian",
    servingSize: 100,
    servingUnit: "g",
    calories: 160,
    protein: 15,
    carbs: 8,
    fat: 9,
    fiber: 4,
  },
  sushi: {
    category: "Malaysian & Asian",
    servingSize: 1,
    servingUnit: "serving",
    calories: 350,
    protein: 16,
    carbs: 55,
    fat: 6,
    fiber: 2,
  },
  sashimi: {
    category: "Malaysian & Asian",
    servingSize: 1,
    servingUnit: "serving",
    calories: 120,
    protein: 24,
    carbs: 0,
    fat: 3,
    fiber: 0,
  },
  "dim sum": {
    category: "Malaysian & Asian",
    servingSize: 1,
    servingUnit: "serving",
    calories: 300,
    protein: 14,
    carbs: 32,
    fat: 12,
    fiber: 2,
  },
  dumplings: {
    category: "Malaysian & Asian",
    servingSize: 1,
    servingUnit: "serving",
    calories: 250,
    protein: 12,
    carbs: 30,
    fat: 8,
    fiber: 2,
  },
  "spring roll": {
    category: "Malaysian & Asian",
    servingSize: 1,
    servingUnit: "piece",
    calories: 150,
    protein: 4,
    carbs: 18,
    fat: 7,
    fiber: 2,
  },
  "roti telur": {
    category: "Malaysian & Asian",
    servingSize: 1,
    servingUnit: "piece",
    calories: 350,
    protein: 10,
    carbs: 38,
    fat: 18,
    fiber: 2,
  },
  "roti tisu": {
    category: "Malaysian & Asian",
    servingSize: 1,
    servingUnit: "piece",
    calories: 380,
    protein: 6,
    carbs: 55,
    fat: 16,
    fiber: 1,
  },
  "roti bom": {
    category: "Malaysian & Asian",
    servingSize: 1,
    servingUnit: "piece",
    calories: 420,
    protein: 7,
    carbs: 45,
    fat: 23,
    fiber: 1,
  },
  murtabak: {
    category: "Malaysian & Asian",
    servingSize: 1,
    servingUnit: "piece",
    calories: 450,
    protein: 20,
    carbs: 38,
    fat: 25,
    fiber: 2,
  },
  thosai: {
    category: "Malaysian & Asian",
    servingSize: 1,
    servingUnit: "piece",
    calories: 180,
    protein: 4,
    carbs: 32,
    fat: 4,
    fiber: 2,
  },
  "putu mayam": {
    category: "Malaysian & Asian",
    servingSize: 1,
    servingUnit: "serving",
    calories: 220,
    protein: 4,
    carbs: 42,
    fat: 4,
    fiber: 2,
  },
  "ayam masak merah": {
    category: "Malaysian & Asian",
    servingSize: 1,
    servingUnit: "serving",
    calories: 380,
    protein: 26,
    carbs: 15,
    fat: 24,
    fiber: 2,
  },
  "ayam goreng berempah": {
    category: "Malaysian & Asian",
    servingSize: 1,
    servingUnit: "piece",
    calories: 330,
    protein: 26,
    carbs: 10,
    fat: 20,
    fiber: 1,
  },
  "ayam percik": {
    category: "Malaysian & Asian",
    servingSize: 1,
    servingUnit: "serving",
    calories: 320,
    protein: 28,
    carbs: 10,
    fat: 18,
    fiber: 1,
  },
  "sambal udang": {
    category: "Malaysian & Asian",
    servingSize: 1,
    servingUnit: "serving",
    calories: 280,
    protein: 20,
    carbs: 10,
    fat: 18,
    fiber: 2,
  },
  "ikan bakar": {
    category: "Malaysian & Asian",
    servingSize: 1,
    servingUnit: "serving",
    calories: 250,
    protein: 30,
    carbs: 3,
    fat: 13,
    fiber: 1,
  },
  "ikan goreng": {
    category: "Malaysian & Asian",
    servingSize: 1,
    servingUnit: "piece",
    calories: 260,
    protein: 24,
    carbs: 5,
    fat: 16,
    fiber: 0,
  },
  "otak-otak": {
    category: "Malaysian & Asian",
    servingSize: 2,
    servingUnit: "pieces",
    calories: 150,
    protein: 12,
    carbs: 6,
    fat: 9,
    fiber: 1,
  },
  "sayur lodeh": {
    category: "Malaysian & Asian",
    servingSize: 1,
    servingUnit: "serving",
    calories: 180,
    protein: 4,
    carbs: 15,
    fat: 12,
    fiber: 4,
  },
  "kangkung belacan": {
    category: "Malaysian & Asian",
    servingSize: 1,
    servingUnit: "serving",
    calories: 130,
    protein: 4,
    carbs: 8,
    fat: 9,
    fiber: 3,
  },
  "ulam-ulaman": {
    category: "Malaysian & Asian",
    servingSize: 1,
    servingUnit: "serving",
    calories: 60,
    protein: 2,
    carbs: 8,
    fat: 2,
    fiber: 4,
  },
  popiah: {
    category: "Malaysian & Asian",
    servingSize: 1,
    servingUnit: "piece",
    calories: 180,
    protein: 6,
    carbs: 28,
    fat: 5,
    fiber: 3,
  },
  "lok lok (skewers)": {
    category: "Malaysian & Asian",
    servingSize: 5,
    servingUnit: "sticks",
    calories: 250,
    protein: 14,
    carbs: 20,
    fat: 14,
    fiber: 2,
  },
  "pisang goreng": {
    category: "Malaysian & Asian",
    servingSize: 2,
    servingUnit: "pieces",
    calories: 250,
    protein: 2,
    carbs: 40,
    fat: 10,
    fiber: 2,
  },
  "cucur udang": {
    category: "Malaysian & Asian",
    servingSize: 2,
    servingUnit: "pieces",
    calories: 220,
    protein: 6,
    carbs: 24,
    fat: 12,
    fiber: 1,
  },
  cendol: {
    category: "Malaysian & Asian",
    servingSize: 1,
    servingUnit: "bowl",
    calories: 300,
    protein: 3,
    carbs: 55,
    fat: 9,
    fiber: 2,
  },
  "ais kacang (abc)": {
    category: "Malaysian & Asian",
    servingSize: 1,
    servingUnit: "bowl",
    calories: 350,
    protein: 4,
    carbs: 70,
    fat: 6,
    fiber: 2,
  },
  kuih: {
    category: "Malaysian & Asian",
    servingSize: 1,
    servingUnit: "piece",
    calories: 120,
    protein: 2,
    carbs: 20,
    fat: 4,
    fiber: 1,
  },
  "kuih lapis": {
    category: "Malaysian & Asian",
    servingSize: 1,
    servingUnit: "piece",
    calories: 140,
    protein: 1,
    carbs: 24,
    fat: 5,
    fiber: 0,
  },
  "onde-onde": {
    category: "Malaysian & Asian",
    servingSize: 4,
    servingUnit: "pieces",
    calories: 180,
    protein: 2,
    carbs: 32,
    fat: 6,
    fiber: 1,
  },
  "apam balik": {
    category: "Malaysian & Asian",
    servingSize: 1,
    servingUnit: "piece",
    calories: 280,
    protein: 5,
    carbs: 40,
    fat: 11,
    fiber: 2,
  },
  "ang ku kueh": {
    category: "Malaysian & Asian",
    servingSize: 1,
    servingUnit: "piece",
    calories: 130,
    protein: 2,
    carbs: 24,
    fat: 3,
    fiber: 2,
  },
  "kuih bahulu": {
    category: "Malaysian & Asian",
    servingSize: 4,
    servingUnit: "pieces",
    calories: 160,
    protein: 4,
    carbs: 28,
    fat: 4,
    fiber: 0,
  },
  "ketupat / lemang": {
    category: "Malaysian & Asian",
    servingSize: 1,
    servingUnit: "piece",
    calories: 150,
    protein: 3,
    carbs: 32,
    fat: 1,
    fiber: 1,
  },
  "curry puff": {
    category: "Malaysian & Asian",
    servingSize: 1,
    servingUnit: "piece",
    calories: 180,
    protein: 4,
    carbs: 20,
    fat: 9,
    fiber: 1,
  },
  vadai: {
    category: "Malaysian & Asian",
    servingSize: 2,
    servingUnit: "pieces",
    calories: 200,
    protein: 7,
    carbs: 22,
    fat: 10,
    fiber: 3,
  },
  keropok: {
    category: "Malaysian & Asian",
    servingSize: 30,
    servingUnit: "g",
    calories: 150,
    protein: 6,
    carbs: 15,
    fat: 8,
    fiber: 0,
  },
  belacan: {
    category: "Malaysian & Asian",
    servingSize: 1,
    servingUnit: "tsp",
    calories: 15,
    protein: 2,
    carbs: 1,
    fat: 0,
    fiber: 0,
  },
  "kicap manis": {
    category: "Malaysian & Asian",
    servingSize: 1,
    servingUnit: "tbsp",
    calories: 30,
    protein: 0,
    carbs: 7,
    fat: 0,
    fiber: 0,
  },
  "santan (coconut milk)": {
    category: "Malaysian & Asian",
    servingSize: 100,
    servingUnit: "ml",
    calories: 230,
    protein: 2,
    carbs: 6,
    fat: 24,
    fiber: 2,
  },
  tauhu: {
    category: "Malaysian & Asian",
    servingSize: 100,
    servingUnit: "g",
    calories: 80,
    protein: 9,
    carbs: 2,
    fat: 4,
    fiber: 0,
  },
  "tauhu sumbat": {
    category: "Malaysian & Asian",
    servingSize: 1,
    servingUnit: "serving",
    calories: 280,
    protein: 12,
    carbs: 30,
    fat: 14,
    fiber: 4,
  },
  cincalok: {
    category: "Malaysian & Asian",
    servingSize: 1,
    servingUnit: "tbsp",
    calories: 20,
    protein: 3,
    carbs: 1,
    fat: 1,
    fiber: 0,
  },

  // ── Western & Fast Food ──────────────────────────────────────────────────
  burger: {
    category: "Western & Fast Food",
    servingSize: 1,
    servingUnit: "piece",
    calories: 500,
    protein: 25,
    carbs: 40,
    fat: 25,
    fiber: 2,
  },
  cheeseburger: {
    category: "Western & Fast Food",
    servingSize: 1,
    servingUnit: "piece",
    calories: 550,
    protein: 28,
    carbs: 42,
    fat: 28,
    fiber: 2,
  },
  "double burger": {
    category: "Western & Fast Food",
    servingSize: 1,
    servingUnit: "piece",
    calories: 750,
    protein: 42,
    carbs: 45,
    fat: 40,
    fiber: 2,
  },
  "pizza slice": {
    category: "Western & Fast Food",
    servingSize: 1,
    servingUnit: "slice",
    calories: 285,
    protein: 12,
    carbs: 36,
    fat: 10,
    fiber: 2,
  },
  sandwich: {
    category: "Western & Fast Food",
    servingSize: 1,
    servingUnit: "piece",
    calories: 350,
    protein: 18,
    carbs: 42,
    fat: 10,
    fiber: 3,
  },
  "club sandwich": {
    category: "Western & Fast Food",
    servingSize: 1,
    servingUnit: "piece",
    calories: 450,
    protein: 28,
    carbs: 45,
    fat: 16,
    fiber: 3,
  },
  "hot dog": {
    category: "Western & Fast Food",
    servingSize: 1,
    servingUnit: "piece",
    calories: 290,
    protein: 12,
    carbs: 24,
    fat: 16,
    fiber: 1,
  },
  "french fries": {
    category: "Western & Fast Food",
    servingSize: 1,
    servingUnit: "serving",
    calories: 365,
    protein: 4,
    carbs: 48,
    fat: 17,
    fiber: 4,
  },
  "chicken nuggets": {
    category: "Western & Fast Food",
    servingSize: 6,
    servingUnit: "pieces",
    calories: 300,
    protein: 18,
    carbs: 20,
    fat: 18,
    fiber: 1,
  },

  // ── Protein & Meat ───────────────────────────────────────────────────────
  "chicken breast": {
    category: "Protein & Meat",
    servingSize: 100,
    servingUnit: "g",
    calories: 165,
    protein: 31,
    carbs: 0,
    fat: 4,
    fiber: 0,
  },
  "raw chicken breast": {
    category: "Protein & Meat",
    servingSize: 100,
    servingUnit: "g",
    calories: 133,
    protein: 25,
    carbs: 0,
    fat: 3,
    fiber: 0,
  },
  "chicken thigh": {
    category: "Protein & Meat",
    servingSize: 100,
    servingUnit: "g",
    calories: 210,
    protein: 26,
    carbs: 0,
    fat: 11,
    fiber: 0,
  },
  "fried chicken": {
    category: "Protein & Meat",
    servingSize: 1,
    servingUnit: "piece",
    calories: 320,
    protein: 28,
    carbs: 12,
    fat: 18,
    fiber: 0,
  },
  "grilled chicken": {
    category: "Protein & Meat",
    servingSize: 100,
    servingUnit: "g",
    calories: 180,
    protein: 33,
    carbs: 0,
    fat: 5,
    fiber: 0,
  },
  beef: {
    category: "Protein & Meat",
    servingSize: 100,
    servingUnit: "g",
    calories: 250,
    protein: 26,
    carbs: 0,
    fat: 16,
    fiber: 0,
  },
  "raw beef": {
    category: "Protein & Meat",
    servingSize: 100,
    servingUnit: "g",
    calories: 215,
    protein: 22,
    carbs: 0,
    fat: 14,
    fiber: 0,
  },
  steak: {
    category: "Protein & Meat",
    servingSize: 100,
    servingUnit: "g",
    calories: 270,
    protein: 28,
    carbs: 0,
    fat: 17,
    fiber: 0,
  },
  pork: {
    category: "Protein & Meat",
    servingSize: 100,
    servingUnit: "g",
    calories: 240,
    protein: 25,
    carbs: 0,
    fat: 15,
    fiber: 0,
  },
  salmon: {
    category: "Protein & Meat",
    servingSize: 100,
    servingUnit: "g",
    calories: 200,
    protein: 27,
    carbs: 0,
    fat: 10,
    fiber: 0,
  },
  "raw salmon": {
    category: "Protein & Meat",
    servingSize: 100,
    servingUnit: "g",
    calories: 142,
    protein: 20,
    carbs: 0,
    fat: 7,
    fiber: 0,
  },
  tuna: {
    category: "Protein & Meat",
    servingSize: 100,
    servingUnit: "g",
    calories: 130,
    protein: 29,
    carbs: 0,
    fat: 1,
    fiber: 0,
  },
  "canned tuna": {
    category: "Protein & Meat",
    servingSize: 1,
    servingUnit: "can",
    calories: 150,
    protein: 32,
    carbs: 0,
    fat: 1,
    fiber: 0,
  },
  shrimp: {
    category: "Protein & Meat",
    servingSize: 100,
    servingUnit: "g",
    calories: 85,
    protein: 18,
    carbs: 1,
    fat: 1,
    fiber: 0,
  },
  "fish fillet": {
    category: "Protein & Meat",
    servingSize: 100,
    servingUnit: "g",
    calories: 150,
    protein: 25,
    carbs: 0,
    fat: 5,
    fiber: 0,
  },
  egg: {
    category: "Protein & Meat",
    servingSize: 1,
    servingUnit: "piece",
    calories: 70,
    protein: 6,
    carbs: 0,
    fat: 5,
    fiber: 0,
  },
  "fried egg": {
    category: "Protein & Meat",
    servingSize: 1,
    servingUnit: "piece",
    calories: 90,
    protein: 6,
    carbs: 0,
    fat: 7,
    fiber: 0,
  },
  "boiled egg": {
    category: "Protein & Meat",
    servingSize: 1,
    servingUnit: "piece",
    calories: 70,
    protein: 6,
    carbs: 0,
    fat: 5,
    fiber: 0,
  },
  "scrambled eggs": {
    category: "Protein & Meat",
    servingSize: 2,
    servingUnit: "eggs",
    calories: 200,
    protein: 14,
    carbs: 2,
    fat: 14,
    fiber: 0,
  },
  omelette: {
    category: "Protein & Meat",
    servingSize: 1,
    servingUnit: "serving",
    calories: 150,
    protein: 11,
    carbs: 2,
    fat: 11,
    fiber: 0,
  },
  "salted egg": {
    category: "Protein & Meat",
    servingSize: 1,
    servingUnit: "piece",
    calories: 80,
    protein: 6,
    carbs: 1,
    fat: 6,
    fiber: 0,
  },
  "century egg": {
    category: "Protein & Meat",
    servingSize: 1,
    servingUnit: "piece",
    calories: 80,
    protein: 6,
    carbs: 1,
    fat: 6,
    fiber: 0,
  },
  "mackerel (ikan kembung)": {
    category: "Protein & Meat",
    servingSize: 100,
    servingUnit: "g",
    calories: 205,
    protein: 19,
    carbs: 0,
    fat: 14,
    fiber: 0,
  },
  "anchovies (ikan bilis)": {
    category: "Protein & Meat",
    servingSize: 30,
    servingUnit: "g",
    calories: 60,
    protein: 9,
    carbs: 0,
    fat: 2,
    fiber: 0,
  },
  "cockles (kerang)": {
    category: "Protein & Meat",
    servingSize: 100,
    servingUnit: "g",
    calories: 80,
    protein: 13,
    carbs: 3,
    fat: 1,
    fiber: 0,
  },
  "squid (sotong)": {
    category: "Protein & Meat",
    servingSize: 100,
    servingUnit: "g",
    calories: 92,
    protein: 16,
    carbs: 3,
    fat: 1,
    fiber: 0,
  },
  "chicken liver": {
    category: "Protein & Meat",
    servingSize: 100,
    servingUnit: "g",
    calories: 167,
    protein: 24,
    carbs: 1,
    fat: 6,
    fiber: 0,
  },
  "minced meat (beef/chicken)": {
    category: "Protein & Meat",
    servingSize: 100,
    servingUnit: "g",
    calories: 215,
    protein: 22,
    carbs: 0,
    fat: 14,
    fiber: 0,
  },
  "char siu (bbq pork)": {
    category: "Protein & Meat",
    servingSize: 100,
    servingUnit: "g",
    calories: 280,
    protein: 24,
    carbs: 12,
    fat: 16,
    fiber: 0,
  },
  "siew yoke (roast pork)": {
    category: "Protein & Meat",
    servingSize: 100,
    servingUnit: "g",
    calories: 330,
    protein: 22,
    carbs: 2,
    fat: 26,
    fiber: 0,
  },
  "fish ball / fish cake": {
    category: "Protein & Meat",
    servingSize: 100,
    servingUnit: "g",
    calories: 120,
    protein: 12,
    carbs: 10,
    fat: 4,
    fiber: 0,
  },

  // ── Grains & Cereals ─────────────────────────────────────────────────────
  "dry oats": {
    category: "Grains & Cereals",
    servingSize: 40,
    servingUnit: "g",
    calories: 156,
    protein: 6,
    carbs: 26,
    fat: 3,
    fiber: 4,
  },
  "raw oats": {
    category: "Grains & Cereals",
    servingSize: 100,
    servingUnit: "g",
    calories: 389,
    protein: 17,
    carbs: 66,
    fat: 7,
    fiber: 10,
  },
  "cooked oats": {
    category: "Grains & Cereals",
    servingSize: 100,
    servingUnit: "g",
    calories: 71,
    protein: 2,
    carbs: 12,
    fat: 2,
    fiber: 2,
  },
  "raw rice": {
    category: "Grains & Cereals",
    servingSize: 100,
    servingUnit: "g",
    calories: 360,
    protein: 7,
    carbs: 79,
    fat: 1,
    fiber: 1,
  },
  "cooked rice": {
    category: "Grains & Cereals",
    servingSize: 100,
    servingUnit: "g",
    calories: 130,
    protein: 3,
    carbs: 28,
    fat: 0,
    fiber: 0,
  },
  "basmati rice": {
    category: "Grains & Cereals",
    servingSize: 100,
    servingUnit: "g",
    calories: 350,
    protein: 8,
    carbs: 77,
    fat: 1,
    fiber: 1,
  },
  "cooked basmati rice": {
    category: "Grains & Cereals",
    servingSize: 100,
    servingUnit: "g",
    calories: 132,
    protein: 3,
    carbs: 29,
    fat: 0,
    fiber: 0,
  },
  "quinoa dry": {
    category: "Grains & Cereals",
    servingSize: 100,
    servingUnit: "g",
    calories: 368,
    protein: 14,
    carbs: 64,
    fat: 6,
    fiber: 7,
  },
  "cooked quinoa": {
    category: "Grains & Cereals",
    servingSize: 100,
    servingUnit: "g",
    calories: 120,
    protein: 4,
    carbs: 21,
    fat: 2,
    fiber: 3,
  },
  pasta: {
    category: "Grains & Cereals",
    servingSize: 100,
    servingUnit: "g",
    calories: 371,
    protein: 13,
    carbs: 74,
    fat: 2,
    fiber: 3,
  },
  "cooked pasta": {
    category: "Grains & Cereals",
    servingSize: 100,
    servingUnit: "g",
    calories: 131,
    protein: 5,
    carbs: 25,
    fat: 1,
    fiber: 2,
  },

  // ── Bread & Bakery ───────────────────────────────────────────────────────
  "white bread": {
    category: "Bread & Bakery",
    servingSize: 1,
    servingUnit: "slice",
    calories: 80,
    protein: 3,
    carbs: 15,
    fat: 1,
    fiber: 1,
  },
  "whole wheat bread": {
    category: "Bread & Bakery",
    servingSize: 1,
    servingUnit: "slice",
    calories: 70,
    protein: 3,
    carbs: 13,
    fat: 1,
    fiber: 2,
  },
  toast: {
    category: "Bread & Bakery",
    servingSize: 1,
    servingUnit: "slice",
    calories: 120,
    protein: 4,
    carbs: 22,
    fat: 2,
    fiber: 1,
  },
  roti: {
    category: "Bread & Bakery",
    servingSize: 1,
    servingUnit: "piece",
    calories: 120,
    protein: 4,
    carbs: 20,
    fat: 3,
    fiber: 1,
  },
  chapati: {
    category: "Bread & Bakery",
    servingSize: 1,
    servingUnit: "piece",
    calories: 100,
    protein: 3,
    carbs: 18,
    fat: 2,
    fiber: 2,
  },
  croissant: {
    category: "Bread & Bakery",
    servingSize: 1,
    servingUnit: "piece",
    calories: 230,
    protein: 5,
    carbs: 26,
    fat: 12,
    fiber: 1,
  },
  muffin: {
    category: "Bread & Bakery",
    servingSize: 1,
    servingUnit: "piece",
    calories: 340,
    protein: 5,
    carbs: 52,
    fat: 13,
    fiber: 1,
  },
  bagel: {
    category: "Bread & Bakery",
    servingSize: 1,
    servingUnit: "piece",
    calories: 270,
    protein: 10,
    carbs: 53,
    fat: 2,
    fiber: 2,
  },
  pita: {
    category: "Bread & Bakery",
    servingSize: 1,
    servingUnit: "piece",
    calories: 160,
    protein: 5,
    carbs: 33,
    fat: 1,
    fiber: 1,
  },

  // ── Vegetables ───────────────────────────────────────────────────────────
  broccoli: {
    category: "Vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 55,
    protein: 4,
    carbs: 11,
    fat: 0,
    fiber: 5,
  },
  spinach: {
    category: "Vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 23,
    protein: 3,
    carbs: 4,
    fat: 0,
    fiber: 2,
  },
  carrot: {
    category: "Vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 52,
    protein: 1,
    carbs: 12,
    fat: 0,
    fiber: 3,
  },
  cucumber: {
    category: "Vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 16,
    protein: 1,
    carbs: 4,
    fat: 0,
    fiber: 1,
  },
  tomato: {
    category: "Vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 35,
    protein: 2,
    carbs: 8,
    fat: 0,
    fiber: 2,
  },
  corn: {
    category: "Vegetables",
    servingSize: 1,
    servingUnit: "cob",
    calories: 130,
    protein: 5,
    carbs: 28,
    fat: 2,
    fiber: 4,
  },
  potato: {
    category: "Vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 160,
    protein: 4,
    carbs: 37,
    fat: 0,
    fiber: 4,
  },
  "sweet potato": {
    category: "Vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 130,
    protein: 2,
    carbs: 30,
    fat: 0,
    fiber: 4,
  },
  "raw sweet potato": {
    category: "Vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 86,
    protein: 2,
    carbs: 20,
    fat: 0,
    fiber: 3,
  },
  avocado: {
    category: "Vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 160,
    protein: 2,
    carbs: 9,
    fat: 15,
    fiber: 7,
  },
  "garden salad": {
    category: "Vegetables",
    servingSize: 1,
    servingUnit: "serving",
    calories: 100,
    protein: 3,
    carbs: 12,
    fat: 5,
    fiber: 4,
  },
  "caesar salad": {
    category: "Vegetables",
    servingSize: 1,
    servingUnit: "serving",
    calories: 350,
    protein: 10,
    carbs: 20,
    fat: 26,
    fiber: 3,
  },
  "kangkung (water spinach)": {
    category: "Vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 30,
    protein: 3,
    carbs: 4,
    fat: 0,
    fiber: 2,
  },
  "long beans (kacang panjang)": {
    category: "Vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 35,
    protein: 3,
    carbs: 6,
    fat: 0,
    fiber: 3,
  },
  "four-angled bean (kacang botol)": {
    category: "Vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 40,
    protein: 3,
    carbs: 6,
    fat: 0,
    fiber: 3,
  },
  "bitter gourd (peria)": {
    category: "Vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 17,
    protein: 1,
    carbs: 4,
    fat: 0,
    fiber: 3,
  },
  "eggplant (terung)": {
    category: "Vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 25,
    protein: 1,
    carbs: 6,
    fat: 0,
    fiber: 3,
  },
  "okra (lady's finger)": {
    category: "Vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 33,
    protein: 2,
    carbs: 7,
    fat: 0,
    fiber: 3,
  },
  "bean sprouts (taugeh)": {
    category: "Vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 30,
    protein: 3,
    carbs: 6,
    fat: 0,
    fiber: 2,
  },
  "chinese cabbage (sawi)": {
    category: "Vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 13,
    protein: 1,
    carbs: 2,
    fat: 0,
    fiber: 1,
  },
  "petai (stink bean)": {
    category: "Vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 145,
    protein: 9,
    carbs: 21,
    fat: 1,
    fiber: 5,
  },
  "pumpkin (labu)": {
    category: "Vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 26,
    protein: 1,
    carbs: 6,
    fat: 0,
    fiber: 1,
  },

  // ── Fruits ───────────────────────────────────────────────────────────────
  apple: {
    category: "Fruits",
    servingSize: 1,
    servingUnit: "piece",
    calories: 95,
    protein: 0,
    carbs: 25,
    fat: 0,
    fiber: 4,
  },
  banana: {
    category: "Fruits",
    servingSize: 1,
    servingUnit: "piece",
    calories: 105,
    protein: 1,
    carbs: 27,
    fat: 0,
    fiber: 3,
  },
  orange: {
    category: "Fruits",
    servingSize: 1,
    servingUnit: "piece",
    calories: 62,
    protein: 1,
    carbs: 15,
    fat: 0,
    fiber: 3,
  },
  mango: {
    category: "Fruits",
    servingSize: 1,
    servingUnit: "piece",
    calories: 200,
    protein: 3,
    carbs: 50,
    fat: 1,
    fiber: 5,
  },
  papaya: {
    category: "Fruits",
    servingSize: 1,
    servingUnit: "serving",
    calories: 120,
    protein: 2,
    carbs: 30,
    fat: 0,
    fiber: 5,
  },
  watermelon: {
    category: "Fruits",
    servingSize: 1,
    servingUnit: "slice",
    calories: 85,
    protein: 2,
    carbs: 21,
    fat: 0,
    fiber: 1,
  },
  grapes: {
    category: "Fruits",
    servingSize: 100,
    servingUnit: "g",
    calories: 100,
    protein: 1,
    carbs: 27,
    fat: 0,
    fiber: 1,
  },
  strawberries: {
    category: "Fruits",
    servingSize: 100,
    servingUnit: "g",
    calories: 50,
    protein: 1,
    carbs: 12,
    fat: 0,
    fiber: 3,
  },
  blueberries: {
    category: "Fruits",
    servingSize: 100,
    servingUnit: "g",
    calories: 85,
    protein: 1,
    carbs: 21,
    fat: 0,
    fiber: 4,
  },
  rambutan: {
    category: "Fruits",
    servingSize: 100,
    servingUnit: "g",
    calories: 75,
    protein: 1,
    carbs: 18,
    fat: 0,
    fiber: 1,
  },
  durian: {
    category: "Fruits",
    servingSize: 100,
    servingUnit: "g",
    calories: 147,
    protein: 2,
    carbs: 27,
    fat: 5,
    fiber: 4,
  },
  "dragon fruit": {
    category: "Fruits",
    servingSize: 100,
    servingUnit: "g",
    calories: 60,
    protein: 1,
    carbs: 13,
    fat: 0,
    fiber: 3,
  },
  starfruit: {
    category: "Fruits",
    servingSize: 1,
    servingUnit: "piece",
    calories: 30,
    protein: 1,
    carbs: 7,
    fat: 0,
    fiber: 3,
  },
  jackfruit: {
    category: "Fruits",
    servingSize: 100,
    servingUnit: "g",
    calories: 95,
    protein: 1,
    carbs: 24,
    fat: 0,
    fiber: 2,
  },
  pomelo: {
    category: "Fruits",
    servingSize: 100,
    servingUnit: "g",
    calories: 38,
    protein: 1,
    carbs: 10,
    fat: 0,
    fiber: 1,
  },
  longan: {
    category: "Fruits",
    servingSize: 100,
    servingUnit: "g",
    calories: 60,
    protein: 1,
    carbs: 15,
    fat: 0,
    fiber: 1,
  },
  guava: {
    category: "Fruits",
    servingSize: 1,
    servingUnit: "piece",
    calories: 68,
    protein: 3,
    carbs: 14,
    fat: 1,
    fiber: 5,
  },
  "rock melon (cantaloupe)": {
    category: "Fruits",
    servingSize: 100,
    servingUnit: "g",
    calories: 34,
    protein: 1,
    carbs: 8,
    fat: 0,
    fiber: 1,
  },
  langsat: {
    category: "Fruits",
    servingSize: 100,
    servingUnit: "g",
    calories: 57,
    protein: 1,
    carbs: 14,
    fat: 0,
    fiber: 2,
  },
  mangosteen: {
    category: "Fruits",
    servingSize: 100,
    servingUnit: "g",
    calories: 73,
    protein: 1,
    carbs: 18,
    fat: 0,
    fiber: 2,
  },
  pineapple: {
    category: "Fruits",
    servingSize: 100,
    servingUnit: "g",
    calories: 50,
    protein: 1,
    carbs: 13,
    fat: 0,
    fiber: 1,
  },

  // ── Dairy ────────────────────────────────────────────────────────────────
  "whole milk": {
    category: "Dairy",
    servingSize: 250,
    servingUnit: "ml",
    calories: 150,
    protein: 8,
    carbs: 12,
    fat: 8,
    fiber: 0,
  },
  "skim milk": {
    category: "Dairy",
    servingSize: 250,
    servingUnit: "ml",
    calories: 90,
    protein: 9,
    carbs: 12,
    fat: 0,
    fiber: 0,
  },
  "oat milk": {
    category: "Dairy",
    servingSize: 250,
    servingUnit: "ml",
    calories: 120,
    protein: 3,
    carbs: 16,
    fat: 5,
    fiber: 2,
  },
  "almond milk": {
    category: "Dairy",
    servingSize: 250,
    servingUnit: "ml",
    calories: 40,
    protein: 1,
    carbs: 2,
    fat: 3,
    fiber: 1,
  },
  yogurt: {
    category: "Dairy",
    servingSize: 1,
    servingUnit: "cup",
    calories: 100,
    protein: 9,
    carbs: 11,
    fat: 3,
    fiber: 0,
  },
  "greek yogurt": {
    category: "Dairy",
    servingSize: 1,
    servingUnit: "cup",
    calories: 130,
    protein: 17,
    carbs: 6,
    fat: 4,
    fiber: 0,
  },
  cheese: {
    category: "Dairy",
    servingSize: 1,
    servingUnit: "slice",
    calories: 110,
    protein: 7,
    carbs: 0,
    fat: 9,
    fiber: 0,
  },
  butter: {
    category: "Dairy",
    servingSize: 1,
    servingUnit: "tbsp",
    calories: 100,
    protein: 0,
    carbs: 0,
    fat: 11,
    fiber: 0,
  },
  "cottage cheese": {
    category: "Dairy",
    servingSize: 100,
    servingUnit: "g",
    calories: 98,
    protein: 11,
    carbs: 3,
    fat: 4,
    fiber: 0,
  },

  // ── Nuts & Seeds ─────────────────────────────────────────────────────────
  "peanut butter": {
    category: "Nuts & Seeds",
    servingSize: 1,
    servingUnit: "tbsp",
    calories: 94,
    protein: 4,
    carbs: 3,
    fat: 8,
    fiber: 1,
  },
  "almond butter": {
    category: "Nuts & Seeds",
    servingSize: 1,
    servingUnit: "tbsp",
    calories: 98,
    protein: 3,
    carbs: 3,
    fat: 9,
    fiber: 2,
  },
  almonds: {
    category: "Nuts & Seeds",
    servingSize: 100,
    servingUnit: "g",
    calories: 579,
    protein: 21,
    carbs: 22,
    fat: 50,
    fiber: 13,
  },
  "cashew nuts": {
    category: "Nuts & Seeds",
    servingSize: 100,
    servingUnit: "g",
    calories: 553,
    protein: 18,
    carbs: 30,
    fat: 44,
    fiber: 3,
  },
  walnuts: {
    category: "Nuts & Seeds",
    servingSize: 100,
    servingUnit: "g",
    calories: 654,
    protein: 15,
    carbs: 14,
    fat: 65,
    fiber: 7,
  },
  "chia seeds": {
    category: "Nuts & Seeds",
    servingSize: 1,
    servingUnit: "tbsp",
    calories: 58,
    protein: 2,
    carbs: 5,
    fat: 4,
    fiber: 4,
  },
  flaxseed: {
    category: "Nuts & Seeds",
    servingSize: 1,
    servingUnit: "tbsp",
    calories: 37,
    protein: 1,
    carbs: 2,
    fat: 3,
    fiber: 2,
  },

  // ── Beverages ────────────────────────────────────────────────────────────
  "black coffee": {
    category: "Beverages",
    servingSize: 1,
    servingUnit: "cup",
    calories: 5,
    protein: 0,
    carbs: 0,
    fat: 0,
    fiber: 0,
  },
  latte: {
    category: "Beverages",
    servingSize: 1,
    servingUnit: "cup",
    calories: 190,
    protein: 8,
    carbs: 19,
    fat: 9,
    fiber: 0,
  },
  cappuccino: {
    category: "Beverages",
    servingSize: 1,
    servingUnit: "cup",
    calories: 120,
    protein: 6,
    carbs: 10,
    fat: 5,
    fiber: 0,
  },
  "green tea": {
    category: "Beverages",
    servingSize: 1,
    servingUnit: "cup",
    calories: 2,
    protein: 0,
    carbs: 0,
    fat: 0,
    fiber: 0,
  },
  "orange juice": {
    category: "Beverages",
    servingSize: 250,
    servingUnit: "ml",
    calories: 110,
    protein: 2,
    carbs: 26,
    fat: 0,
    fiber: 0,
  },
  "apple juice": {
    category: "Beverages",
    servingSize: 250,
    servingUnit: "ml",
    calories: 115,
    protein: 0,
    carbs: 28,
    fat: 0,
    fiber: 0,
  },
  "coca cola": {
    category: "Beverages",
    servingSize: 1,
    servingUnit: "can",
    calories: 140,
    protein: 0,
    carbs: 39,
    fat: 0,
    fiber: 0,
  },
  pepsi: {
    category: "Beverages",
    servingSize: 1,
    servingUnit: "can",
    calories: 150,
    protein: 0,
    carbs: 41,
    fat: 0,
    fiber: 0,
  },
  beer: {
    category: "Beverages",
    servingSize: 1,
    servingUnit: "can",
    calories: 150,
    protein: 1,
    carbs: 13,
    fat: 0,
    fiber: 0,
  },
  wine: {
    category: "Beverages",
    servingSize: 1,
    servingUnit: "glass",
    calories: 125,
    protein: 0,
    carbs: 4,
    fat: 0,
    fiber: 0,
  },
  "kopi (with condensed milk)": {
    category: "Beverages",
    servingSize: 1,
    servingUnit: "cup",
    calories: 110,
    protein: 2,
    carbs: 18,
    fat: 4,
    fiber: 0,
  },
  "kopi o": {
    category: "Beverages",
    servingSize: 1,
    servingUnit: "cup",
    calories: 60,
    protein: 0,
    carbs: 14,
    fat: 0,
    fiber: 0,
  },
  "kopi c": {
    category: "Beverages",
    servingSize: 1,
    servingUnit: "cup",
    calories: 90,
    protein: 1,
    carbs: 16,
    fat: 3,
    fiber: 0,
  },
  "teh (with condensed milk)": {
    category: "Beverages",
    servingSize: 1,
    servingUnit: "cup",
    calories: 110,
    protein: 2,
    carbs: 18,
    fat: 4,
    fiber: 0,
  },
  "teh o": {
    category: "Beverages",
    servingSize: 1,
    servingUnit: "cup",
    calories: 50,
    protein: 0,
    carbs: 13,
    fat: 0,
    fiber: 0,
  },
  "teh c": {
    category: "Beverages",
    servingSize: 1,
    servingUnit: "cup",
    calories: 90,
    protein: 1,
    carbs: 15,
    fat: 3,
    fiber: 0,
  },
  "sirap bandung": {
    category: "Beverages",
    servingSize: 1,
    servingUnit: "glass",
    calories: 180,
    protein: 2,
    carbs: 36,
    fat: 3,
    fiber: 0,
  },
  "sirap limau / air limau": {
    category: "Beverages",
    servingSize: 1,
    servingUnit: "glass",
    calories: 100,
    protein: 0,
    carbs: 25,
    fat: 0,
    fiber: 0,
  },
  "air kelapa (coconut water)": {
    category: "Beverages",
    servingSize: 250,
    servingUnit: "ml",
    calories: 45,
    protein: 2,
    carbs: 9,
    fat: 0,
    fiber: 1,
  },
  "sugar cane juice": {
    category: "Beverages",
    servingSize: 1,
    servingUnit: "glass",
    calories: 180,
    protein: 0,
    carbs: 45,
    fat: 0,
    fiber: 0,
  },
  "milo ais": {
    category: "Beverages",
    servingSize: 1,
    servingUnit: "glass",
    calories: 200,
    protein: 5,
    carbs: 35,
    fat: 6,
    fiber: 1,
  },
  "100plus / isotonic drink": {
    category: "Beverages",
    servingSize: 1,
    servingUnit: "can",
    calories: 90,
    protein: 0,
    carbs: 22,
    fat: 0,
    fiber: 0,
  },
  "soy milk (fresh)": {
    category: "Beverages",
    servingSize: 250,
    servingUnit: "ml",
    calories: 90,
    protein: 6,
    carbs: 10,
    fat: 3,
    fiber: 1,
  },
  "barley drink": {
    category: "Beverages",
    servingSize: 250,
    servingUnit: "ml",
    calories: 90,
    protein: 1,
    carbs: 22,
    fat: 0,
    fiber: 1,
  },
  "chrysanthemum tea": {
    category: "Beverages",
    servingSize: 250,
    servingUnit: "ml",
    calories: 50,
    protein: 0,
    carbs: 13,
    fat: 0,
    fiber: 0,
  },

  // ── Snacks & Desserts ────────────────────────────────────────────────────
  "chocolate bar": {
    category: "Snacks & Desserts",
    servingSize: 1,
    servingUnit: "bar",
    calories: 230,
    protein: 3,
    carbs: 30,
    fat: 12,
    fiber: 2,
  },
  cake: {
    category: "Snacks & Desserts",
    servingSize: 1,
    servingUnit: "slice",
    calories: 350,
    protein: 4,
    carbs: 52,
    fat: 14,
    fiber: 1,
  },
  "ice cream": {
    category: "Snacks & Desserts",
    servingSize: 1,
    servingUnit: "scoop",
    calories: 135,
    protein: 2,
    carbs: 17,
    fat: 7,
    fiber: 0,
  },
  cookie: {
    category: "Snacks & Desserts",
    servingSize: 1,
    servingUnit: "piece",
    calories: 150,
    protein: 2,
    carbs: 22,
    fat: 6,
    fiber: 1,
  },
  chips: {
    category: "Snacks & Desserts",
    servingSize: 100,
    servingUnit: "g",
    calories: 536,
    protein: 7,
    carbs: 53,
    fat: 35,
    fiber: 5,
  },
  popcorn: {
    category: "Snacks & Desserts",
    servingSize: 100,
    servingUnit: "g",
    calories: 375,
    protein: 11,
    carbs: 74,
    fat: 4,
    fiber: 15,
  },
  "protein bar": {
    category: "Snacks & Desserts",
    servingSize: 1,
    servingUnit: "bar",
    calories: 200,
    protein: 20,
    carbs: 22,
    fat: 5,
    fiber: 3,
  },
  "kacang putih": {
    category: "Snacks & Desserts",
    servingSize: 50,
    servingUnit: "g",
    calories: 270,
    protein: 10,
    carbs: 15,
    fat: 19,
    fiber: 4,
  },
  "kuih kapit (love letters)": {
    category: "Snacks & Desserts",
    servingSize: 2,
    servingUnit: "pieces",
    calories: 110,
    protein: 1,
    carbs: 16,
    fat: 5,
    fiber: 0,
  },
  "tau sar piah": {
    category: "Snacks & Desserts",
    servingSize: 1,
    servingUnit: "piece",
    calories: 180,
    protein: 4,
    carbs: 28,
    fat: 6,
    fiber: 2,
  },
  "egg tart": {
    category: "Snacks & Desserts",
    servingSize: 1,
    servingUnit: "piece",
    calories: 220,
    protein: 4,
    carbs: 22,
    fat: 13,
    fiber: 0,
  },
  "pineapple tart": {
    category: "Snacks & Desserts",
    servingSize: 2,
    servingUnit: "pieces",
    calories: 180,
    protein: 2,
    carbs: 26,
    fat: 8,
    fiber: 1,
  },
  "bubur cha cha": {
    category: "Snacks & Desserts",
    servingSize: 1,
    servingUnit: "bowl",
    calories: 280,
    protein: 3,
    carbs: 48,
    fat: 9,
    fiber: 3,
  },

  // ── Supplements ──────────────────────────────────────────────────────────
  "protein shake": {
    category: "Supplements",
    servingSize: 1,
    servingUnit: "portion",
    calories: 100,
    protein: 21,
    carbs: 3,
    fat: 2,
    fiber: 0,
  },
  "whey protein": {
    category: "Supplements",
    servingSize: 30,
    servingUnit: "g",
    calories: 120,
    protein: 24,
    carbs: 3,
    fat: 2,
    fiber: 0,
  },
  "mass gainer": {
    category: "Supplements",
    servingSize: 1,
    servingUnit: "scoop",
    calories: 400,
    protein: 30,
    carbs: 60,
    fat: 5,
    fiber: 3,
  },
  creatine: {
    category: "Supplements",
    servingSize: 5,
    servingUnit: "g",
    calories: 0,
    protein: 0,
    carbs: 0,
    fat: 0,
    fiber: 0,
  },

  //Custom Foods
  "tuna dip": {
    category: "Custom Foods",
    servingSize: 1,
    servingUnit: "portion",
    calories: 380,
    protein: 46,
    carbs: 5,
    fat: 20,
    fiber: 0,
  },
  "custom food 2": {
    category: "Custom Foods",
    servingSize: 1,
    servingUnit: "g",
    calories: 0,
    protein: 0,
    carbs: 0,
    fat: 0,
    fiber: 0,
  },
  "custom food 3": {
    category: "Custom Foods",
    servingSize: 100,
    servingUnit: "g",
    calories: 0,
    protein: 0,
    carbs: 0,
    fat: 0,
    fiber: 0,
  },
  "custom food 4": {
    category: "Custom Foods",
    servingSize: 100,
    servingUnit: "g",
    calories: 0,
    protein: 0,
    carbs: 0,
    fat: 0,
    fiber: 0,
  },
};

// ── Helpers ───────────────────────────────────────────────────────────────

function toTitleCase(str) {
  return str.replace(/\b\w/g, (c) => c.toUpperCase());
}

export function getCategories() {
  return CATEGORY_ORDER.filter((cat) =>
    Object.values(FOOD_DATABASE).some((e) => e.category === cat),
  );
}

export function getFoodsByCategory(category) {
  return Object.entries(FOOD_DATABASE)
    .filter(([, e]) => e.category === category)
    .map(([key, e]) => ({
      key,
      label: toTitleCase(key),
      servingSize: e.servingSize,
      servingUnit: e.servingUnit,
    }))
    .sort((a, b) => a.label.localeCompare(b.label));
}

/**
 * Scale nutrition for a food key to the entered quantity.
 * multiplier = enteredQty / servingSize
 */
export function calculateNutrition(key, quantity) {
  const e = FOOD_DATABASE[key];
  if (!e || !quantity || quantity <= 0) return null;

  const m = quantity / e.servingSize;
  return {
    calories: Math.round(e.calories * m),
    protein: Math.round(e.protein * m),
    carbs: Math.round(e.carbs * m),
    fat: Math.round(e.fat * m),
    fiber: Math.round(e.fiber * m),
    multiplier: m,
  };
}

export function toTitleCasePublic(str) {
  return toTitleCase(str);
}

export default FOOD_DATABASE;
